# Generated by Django 5.1.7 on 2025-04-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('przepisowo', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation_method',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
